# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b3ed95b18711ec79f25f42cba09ca12fb05562a20071df13ff41269b167b2c94fbc60f1ef8bbfeb48083e5bfc34a5e53c611617aa34858b69b7efed1fbba3de

test:
  secret_key_base: e75f06eb885eb342d4fd4ca1b2e2ea3e9c3566b6f35c2ba0aae1150be4f01aa9427ce28476b8c426f2f15e190f88a2a75a65ef5bf54b29b3b625dde3821ebb43

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
