# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c236abea03198da498ba8aef3628b344569e1091ef534492f1eb19ced895b6612b48255ceeb82eae0202741c4c563d2d75d3dee8731729c890da7dea9902cb53

test:
  secret_key_base: 22eb52df7c9d1b63b6f880932e196010955f54997e6686c9505fad6b113b89841d943ba5a192c5ebdadca1ad974a539c128baa26a3dba51595d1227d578c6dee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
